export const ROLES = {
  ADMIN: "ADMIN",
  EDITOR: "EDITOR",
  MEMBER: "MEMBER",
  CUSTOMER: "CUSTOMER",
  ADMIN_EDITOR: ["ADMIN", "EDITOR"],
  ADMIN_EDITOR_MEMBER: ["ADMIN", "EDITOR", "MEMBER"],
  ADMIN_EDITOR_MEMBER_CUSTOMER: ["ADMIN", "EDITOR", "MEMBER", "CUSTOMER"],
};
